use utoipa::OpenApi;
use utoipa::openapi::OpenApi as ApiDocs;

use crate::models::*;

use crate::routes::user; // need * to import hidden structs generated by utoipa

#[derive(OpenApi)]
#[openapi(
  paths(
    // User endpoints
    user::all,
    user::new
  ),
  components(schemas(User)),
  tags(
    (name = "bzapi", description = "buzzysin's API")
  )
)]
pub struct ApiDoc;

pub fn openapi() -> ApiDocs {
    ApiDoc::openapi()
}
